// components/home/energy-chart.tsx
"use client"

import { Card, CardContent } from "@/components/ui/card";
import { Area, AreaChart, ResponsiveContainer, XAxis, YAxis, Tooltip } from "recharts";

const data = [
    { time: "13:00", value: 50 },
    { time: "14:00", value: 120 },
    { time: "15:00", value: 140 },
    { time: "16:00", value: 100 },
    { time: "17:00", value: 80 },
    { time: "18:00", value: 110 },
];

export function EnergyChart() {

    return (
        <Card className="bg-background border-border">
            <CardContent className="p-4">
                <div className="flex justify-between items-center mb-6">
                    <div>
                        <div className="text-muted-foreground text-sm">
                            Electricity generated by solar
                        </div>
                        <div className="text-2xl font-semibold text-foreground">140.65KWh</div>
                    </div>
                    <div className="flex items-center gap-2">
                        <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
                        <span className="text-sm text-muted-foreground">Live</span>
                    </div>
                </div>

                <div className="w-full h-[200px] mt-4">
                    <ResponsiveContainer width="100%" height="100%">
                        <AreaChart
                            data={data}
                            margin={{
                                top: 10,
                                right: 10,
                                left: 0,
                                bottom: 0
                            }}
                        >
                            <defs>
                                <linearGradient id="colorValue" x1="0" y1="0" x2="0" y2="1">
                                    <stop
                                        offset="5%"
                                        stopColor="#22c55e"
                                        stopOpacity={0.3}
                                    />
                                    <stop
                                        offset="95%"
                                        stopColor="#22c55e"
                                        stopOpacity={0}
                                    />
                                </linearGradient>
                            </defs>
                            <XAxis
                                dataKey="time"
                                axisLine={false}
                                tickLine={false}
                                tick={{
                                    fill: '#94a3b8',
                                    fontSize: 12
                                }}
                                dy={10}
                            />
                            <YAxis
                                axisLine={false}
                                tickLine={false}
                                tick={{
                                    fill: '#94a3b8',
                                    fontSize: 12
                                }}
                                tickFormatter={(value) => `${value}kWh`}
                                dx={-10}
                            />
                            <Tooltip
                                contentStyle={{
                                    backgroundColor: '#1f2937',
                                    border: 'none',
                                    borderRadius: '8px',
                                    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
                                }}
                                itemStyle={{
                                    color: '#94a3b8',
                                }}
                                formatter={(value: number) => [`${value}kWh`, 'Generated']}
                                labelStyle={{
                                    color: '#e2e8f0',
                                }}
                            />
                            <Area
                                type="monotone"
                                dataKey="value"
                                stroke="#22c55e"
                                fill="url(#colorValue)"
                                strokeWidth={2}
                            />
                        </AreaChart>
                    </ResponsiveContainer>
                </div>
            </CardContent>
        </Card>
    );
}